// backend/seeds/seedProductsNew.js
const mongoose = require('mongoose');
const path = require('path');
const colors = require('colors');

// Load environment variables
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

// Load actual models
const Product = require('../models/Product');
const Category = require('../models/Category');
const Collection = require('../models/Collection');

const connectDB = async () => {
  const uri = process.env.MONGO_URI || process.env.MONGODB_URI;
  console.log('🔗 Connecting to MongoDB...'.cyan);
  await mongoose.connect(uri);
  console.log('✅ Connected to MongoDB'.green);
};

// 29 products paired with actual uploaded images
const getProducts = (categoryIds, collectionIds) => {
  // Helper to pick random items from an array
  const pick = (arr, n = 1) => {
    const shuffled = [...arr].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, n);
  };

  const allCatIds = Object.values(categoryIds);
  const allColIds = Object.values(collectionIds);

  return [
    // Product 1
    {
      name: 'Robe Fleurie Printemps',
      slug: 'robe-fleurie-printemps',
      description: 'Magnifique robe fleurie légère et aérienne, parfaite pour les journées ensoleillées. Tissu respirant et confortable avec une coupe flatteuse.',
      price: 129.90,
      comparePrice: 169.90,
      images: [
        '/uploads/products/images-1769729661582-60741290.jpg',
        '/uploads/products/images-1769729661582-837255541.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Rose', 'Blanc'],
      stock: 45,
      sku: 'ROB-FLE-001',
      featured: true,
      bestseller: true,
      isActive: true,
      tags: ['robe', 'fleurie', 'printemps', 'élégante'],
      materials: ['Polyester', 'Coton'],
      careInstructions: 'Lavage à 30°C, repassage à basse température',
      weight: 0.3,
      rating: { average: 4.8, count: 24 },
      views: 320,
      soldCount: 67,
    },
    // Product 2
    {
      name: 'Ensemble Casual Moderne',
      slug: 'ensemble-casual-moderne',
      description: 'Ensemble deux pièces parfait pour un look casual chic. Confortable et stylé pour votre quotidien avec des finitions soignées.',
      price: 89.90,
      comparePrice: 119.90,
      images: [
        '/uploads/products/images-1769732563048-147185426.jpg',
        '/uploads/products/images-1769732563049-666601931.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Beige', 'Noir'],
      stock: 60,
      sku: 'ENS-CAS-001',
      featured: true,
      bestseller: false,
      isActive: true,
      tags: ['ensemble', 'casual', 'moderne', 'quotidien'],
      materials: ['Coton', 'Élasthanne'],
      careInstructions: 'Lavage en machine à 30°C',
      weight: 0.45,
      rating: { average: 4.5, count: 18 },
      views: 245,
      soldCount: 42,
    },
    // Product 3
    {
      name: 'Robe Longue Bohème',
      slug: 'robe-longue-boheme',
      description: 'Robe longue au style bohème chic avec des motifs délicats. Parfaite pour les soirées d\'été et les occasions spéciales.',
      price: 149.90,
      comparePrice: 199.90,
      images: [
        '/uploads/products/images-1769732603169-605581584.jpg',
        '/uploads/products/images-1769732603169-709907797.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L'],
      colors: ['Bordeaux', 'Vert émeraude'],
      stock: 35,
      sku: 'ROB-BOH-001',
      featured: true,
      bestseller: true,
      isActive: true,
      tags: ['robe', 'longue', 'bohème', 'été'],
      materials: ['Viscose', 'Lin'],
      careInstructions: 'Lavage délicat à la main',
      weight: 0.35,
      rating: { average: 4.9, count: 31 },
      views: 410,
      soldCount: 89,
    },
    // Product 4
    {
      name: 'Top Élégant à Volants',
      slug: 'top-elegant-volants',
      description: 'Top féminin avec des volants délicats et une coupe moderne. Idéal pour un look sophistiqué au bureau ou en soirée.',
      price: 59.90,
      comparePrice: 79.90,
      images: [
        '/uploads/products/images-1769732603169-890915369.jpg',
        '/uploads/products/images-1769732603171-718414639.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Blanc', 'Rose poudré', 'Noir'],
      stock: 80,
      sku: 'TOP-VOL-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['top', 'volants', 'élégant', 'bureau'],
      materials: ['Polyester', 'Soie'],
      careInstructions: 'Lavage délicat à 30°C',
      weight: 0.2,
      rating: { average: 4.3, count: 12 },
      views: 180,
      soldCount: 28,
    },
    // Product 5
    {
      name: 'Pantalon Tailleur Chic',
      slug: 'pantalon-tailleur-chic',
      description: 'Pantalon tailleur coupe droite avec une finition premium. Parfait pour le bureau ou les événements formels.',
      price: 79.90,
      comparePrice: 109.90,
      images: [
        '/uploads/products/images-1769732937694-616884695.jpg',
        '/uploads/products/images-1769732937694-804713680.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['36', '38', '40', '42', '44'],
      colors: ['Noir', 'Gris anthracite', 'Bleu marine'],
      stock: 55,
      sku: 'PAN-TAI-001',
      featured: false,
      bestseller: true,
      isActive: true,
      tags: ['pantalon', 'tailleur', 'formel', 'bureau'],
      materials: ['Polyester', 'Viscose'],
      careInstructions: 'Nettoyage à sec recommandé',
      weight: 0.4,
      rating: { average: 4.6, count: 22 },
      views: 290,
      soldCount: 55,
    },
    // Product 6
    {
      name: 'Jupe Plissée Midi',
      slug: 'jupe-plissee-midi',
      description: 'Jupe plissée midi élégante et fluide. Un classique intemporel qui s\'adapte à toutes les silhouettes.',
      price: 69.90,
      comparePrice: 89.90,
      images: [
        '/uploads/products/images-1769732961207-313545229.jpg',
        '/uploads/products/images-1769732961207-935489790.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Beige', 'Noir', 'Kaki'],
      stock: 40,
      sku: 'JUP-PLI-001',
      featured: true,
      bestseller: false,
      isActive: true,
      tags: ['jupe', 'plissée', 'midi', 'classique'],
      materials: ['Polyester'],
      careInstructions: 'Lavage à 30°C, ne pas essorer',
      weight: 0.25,
      rating: { average: 4.4, count: 15 },
      views: 200,
      soldCount: 33,
    },
    // Product 7
    {
      name: 'Chemise Oversize en Lin',
      slug: 'chemise-oversize-lin',
      description: 'Chemise oversize en lin naturel, légère et respirante. Parfaite pour un style décontracté et tendance.',
      price: 74.90,
      comparePrice: 99.90,
      images: [
        '/uploads/products/images-1769732972239-802082040.jpg',
        '/uploads/products/images-1769732972239-950234806.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Blanc', 'Bleu ciel', 'Beige'],
      stock: 65,
      sku: 'CHE-OVR-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['chemise', 'oversize', 'lin', 'décontracté'],
      materials: ['Lin', 'Coton'],
      careInstructions: 'Lavage à 40°C, repassage vapeur',
      weight: 0.25,
      rating: { average: 4.2, count: 9 },
      views: 155,
      soldCount: 21,
    },
    // Product 8
    {
      name: 'Veste Blazer Femme',
      slug: 'veste-blazer-femme',
      description: 'Blazer structuré et moderne pour un look professionnel impeccable. Doublure soyeuse et finitions premium.',
      price: 139.90,
      comparePrice: 189.90,
      images: [
        '/uploads/products/images-1769732979231-500164001.jpg',
        '/uploads/products/images-1769732979231-643944372.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Noir', 'Beige', 'Rose'],
      stock: 30,
      sku: 'VES-BLA-001',
      featured: true,
      bestseller: true,
      isActive: true,
      tags: ['veste', 'blazer', 'professionnel', 'chic'],
      materials: ['Polyester', 'Élasthanne'],
      careInstructions: 'Nettoyage à sec',
      weight: 0.55,
      rating: { average: 4.7, count: 28 },
      views: 380,
      soldCount: 72,
    },
    // Product 9
    {
      name: 'Robe de Soirée Pailletée',
      slug: 'robe-soiree-pailletee',
      description: 'Robe de soirée scintillante avec des paillettes fines. Parfaite pour vos événements les plus glamour.',
      price: 199.90,
      comparePrice: 269.90,
      images: [
        '/uploads/products/images-1769732998537-258575964.jpg',
        '/uploads/products/images-1769732998538-940142523.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L'],
      colors: ['Or', 'Argent', 'Noir'],
      stock: 20,
      sku: 'ROB-SOI-001',
      featured: true,
      bestseller: false,
      isActive: true,
      tags: ['robe', 'soirée', 'paillettes', 'glamour'],
      materials: ['Polyester', 'Sequins'],
      careInstructions: 'Nettoyage à sec uniquement',
      weight: 0.5,
      rating: { average: 4.9, count: 35 },
      views: 520,
      soldCount: 45,
    },
    // Product 10
    {
      name: 'Jean Slim Taille Haute',
      slug: 'jean-slim-taille-haute',
      description: 'Jean slim taille haute avec un stretch confortable. Coupe ajustée qui met en valeur votre silhouette.',
      price: 89.90,
      comparePrice: 119.90,
      images: [
        '/uploads/products/images-1769733076747-972248947.jpg',
        '/uploads/products/images-1769733076749-339504763.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['34', '36', '38', '40', '42', '44'],
      colors: ['Bleu foncé', 'Noir', 'Bleu clair'],
      stock: 90,
      sku: 'JEA-SLI-001',
      featured: false,
      bestseller: true,
      isActive: true,
      tags: ['jean', 'slim', 'taille haute', 'stretch'],
      materials: ['Denim', 'Élasthanne'],
      careInstructions: 'Lavage à 30°C, retourner avant lavage',
      weight: 0.5,
      rating: { average: 4.5, count: 42 },
      views: 450,
      soldCount: 110,
    },
    // Product 11
    {
      name: 'Combinaison Jumpsuit Chic',
      slug: 'combinaison-jumpsuit-chic',
      description: 'Combinaison élégante avec ceinture à nouer. Un look complet en une seule pièce pour un style raffiné.',
      price: 119.90,
      comparePrice: 159.90,
      images: [
        '/uploads/products/images-1769733616152-384431398.jpg',
        '/uploads/products/images-1769733616152-472167711.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Noir', 'Camel', 'Vert olive'],
      stock: 35,
      sku: 'COM-JUM-001',
      featured: true,
      bestseller: false,
      isActive: true,
      tags: ['combinaison', 'jumpsuit', 'chic', 'ceinture'],
      materials: ['Viscose', 'Polyester'],
      careInstructions: 'Lavage délicat à 30°C',
      weight: 0.4,
      rating: { average: 4.6, count: 19 },
      views: 275,
      soldCount: 38,
    },
    // Product 12 (3 images - the timestamp group with 3 files)
    {
      name: 'Robe Midi Satinée',
      slug: 'robe-midi-satinee',
      description: 'Robe midi en satin luxueux avec un tombé parfait. Idéale pour les cocktails et les dîners élégants.',
      price: 159.90,
      comparePrice: 209.90,
      images: [
        '/uploads/products/images-1769733625299-295534529.jpg',
        '/uploads/products/images-1769733625300-143908030.jpg',
        '/uploads/products/images-1769733625301-740563729.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L'],
      colors: ['Champagne', 'Bordeaux', 'Bleu nuit'],
      stock: 25,
      sku: 'ROB-SAT-001',
      featured: true,
      bestseller: true,
      isActive: true,
      tags: ['robe', 'midi', 'satin', 'cocktail', 'luxe'],
      materials: ['Satin', 'Polyester'],
      careInstructions: 'Nettoyage à sec recommandé',
      weight: 0.35,
      rating: { average: 4.8, count: 27 },
      views: 390,
      soldCount: 61,
    },
    // Product 13
    {
      name: 'Cardigan Long Tricot',
      slug: 'cardigan-long-tricot',
      description: 'Cardigan long en tricot doux et chaud. Parfait pour les journées fraîches, à porter sur n\'importe quelle tenue.',
      price: 84.90,
      comparePrice: 109.90,
      images: [
        '/uploads/products/images-1769733634496-358022781.jpg',
        '/uploads/products/images-1769733634496-564710434.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Gris', 'Beige', 'Noir'],
      stock: 50,
      sku: 'CAR-TRI-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['cardigan', 'tricot', 'long', 'hiver'],
      materials: ['Acrylique', 'Laine'],
      careInstructions: 'Lavage à 30°C en programme laine',
      weight: 0.45,
      rating: { average: 4.3, count: 14 },
      views: 165,
      soldCount: 25,
    },
    // Product 14
    {
      name: 'Short Taille Haute Élégant',
      slug: 'short-taille-haute-elegant',
      description: 'Short taille haute avec plis devant pour un look structuré et féminin. Idéal pour l\'été.',
      price: 54.90,
      comparePrice: 74.90,
      images: [
        '/uploads/products/images-1769733643795-241542693.jpg',
        '/uploads/products/images-1769733643795-456288677.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Blanc', 'Beige', 'Bleu ciel'],
      stock: 70,
      sku: 'SHO-TAI-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['short', 'taille haute', 'été', 'féminin'],
      materials: ['Coton', 'Lin'],
      careInstructions: 'Lavage en machine à 30°C',
      weight: 0.2,
      rating: { average: 4.1, count: 8 },
      views: 130,
      soldCount: 19,
    },
    // Product 15
    {
      name: 'Tunique Brodée Orientale',
      slug: 'tunique-brodee-orientale',
      description: 'Tunique avec des broderies orientales raffinées. Un mélange parfait de tradition et de modernité.',
      price: 94.90,
      comparePrice: 129.90,
      images: [
        '/uploads/products/images-1769733652399-217320620.jpg',
        '/uploads/products/images-1769733652402-637461528.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Blanc', 'Bleu', 'Rose'],
      stock: 40,
      sku: 'TUN-BRO-001',
      featured: true,
      bestseller: false,
      isActive: true,
      tags: ['tunique', 'brodée', 'orientale', 'traditionnelle'],
      materials: ['Coton', 'Fil de soie'],
      careInstructions: 'Lavage à la main recommandé',
      weight: 0.3,
      rating: { average: 4.7, count: 20 },
      views: 310,
      soldCount: 48,
    },
    // Product 16
    {
      name: 'Manteau Long Classique',
      slug: 'manteau-long-classique',
      description: 'Manteau long et élégant en laine mélangée. Une pièce essentielle pour les saisons froides avec une coupe cintrée.',
      price: 189.90,
      comparePrice: 249.90,
      images: [
        '/uploads/products/images-1769733659342-929845986.jpg',
        '/uploads/products/images-1769733659346-539773795.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Camel', 'Noir', 'Gris'],
      stock: 25,
      sku: 'MAN-CLA-001',
      featured: true,
      bestseller: true,
      isActive: true,
      tags: ['manteau', 'long', 'classique', 'hiver', 'laine'],
      materials: ['Laine', 'Polyester'],
      careInstructions: 'Nettoyage à sec uniquement',
      weight: 1.2,
      rating: { average: 4.8, count: 32 },
      views: 420,
      soldCount: 58,
    },
    // Product 17
    {
      name: 'Blouse Transparente à Pois',
      slug: 'blouse-transparente-pois',
      description: 'Blouse légère et délicate avec motifs à pois. Un basique chic pour un style féminin et romantique.',
      price: 49.90,
      comparePrice: 69.90,
      images: [
        '/uploads/products/images-1769737828052-117393681.jpg',
        '/uploads/products/images-1769737828053-600184371.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['XS', 'S', 'M', 'L'],
      colors: ['Noir', 'Blanc', 'Rouge'],
      stock: 75,
      sku: 'BLO-POI-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['blouse', 'transparente', 'pois', 'romantique'],
      materials: ['Mousseline', 'Polyester'],
      careInstructions: 'Lavage délicat à 30°C',
      weight: 0.15,
      rating: { average: 4.0, count: 7 },
      views: 120,
      soldCount: 15,
    },
    // Product 18
    {
      name: 'Pantalon Large Palazzo',
      slug: 'pantalon-large-palazzo',
      description: 'Pantalon palazzo fluide et confortable avec une taille élastiquée. Élégant et facile à porter au quotidien.',
      price: 74.90,
      comparePrice: 99.90,
      images: [
        '/uploads/products/images-1769737838447-501189951.jpg',
        '/uploads/products/images-1769737838447-813366030.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Noir', 'Beige', 'Kaki'],
      stock: 60,
      sku: 'PAN-PAL-001',
      featured: false,
      bestseller: true,
      isActive: true,
      tags: ['pantalon', 'palazzo', 'large', 'fluide', 'confort'],
      materials: ['Viscose', 'Lin'],
      careInstructions: 'Lavage en machine à 30°C',
      weight: 0.35,
      rating: { average: 4.4, count: 16 },
      views: 210,
      soldCount: 37,
    },
    // Product 19
    {
      name: 'Pull Col Roulé Fin',
      slug: 'pull-col-roule-fin',
      description: 'Pull col roulé en maille fine, doux et chaud. Un essentiel du dressing hivernal facile à assortir.',
      price: 64.90,
      comparePrice: 84.90,
      images: [
        '/uploads/products/images-1769737846144-85027966.jpg',
        '/uploads/products/images-1769737846146-269014180.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Noir', 'Crème', 'Bordeaux', 'Gris'],
      stock: 85,
      sku: 'PUL-COL-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['pull', 'col roulé', 'maille', 'hiver'],
      materials: ['Laine mérinos', 'Acrylique'],
      careInstructions: 'Lavage à 30°C programme délicat',
      weight: 0.35,
      rating: { average: 4.3, count: 11 },
      views: 170,
      soldCount: 29,
    },
    // Product 20
    {
      name: 'Robe Chemise Rayée',
      slug: 'robe-chemise-rayee',
      description: 'Robe chemise avec un imprimé à rayures classiques. Polyvalente et chic, à porter ceinturée ou fluide.',
      price: 99.90,
      comparePrice: 139.90,
      images: [
        '/uploads/products/images-1769737856233-315021277.jpg',
        '/uploads/products/images-1769737856234-668223470.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Bleu/Blanc', 'Noir/Blanc'],
      stock: 45,
      sku: 'ROB-CHE-001',
      featured: true,
      bestseller: false,
      isActive: true,
      tags: ['robe', 'chemise', 'rayée', 'classique'],
      materials: ['Coton', 'Polyester'],
      careInstructions: 'Lavage en machine à 40°C',
      weight: 0.3,
      rating: { average: 4.5, count: 17 },
      views: 230,
      soldCount: 34,
    },
    // Product 21
    {
      name: 'Crop Top Côtelé Stretch',
      slug: 'crop-top-cotele-stretch',
      description: 'Crop top côtelé moulant et stretch. Un basique sexy et confortable à combiner avec pantalons ou jupes taille haute.',
      price: 34.90,
      comparePrice: 49.90,
      images: [
        '/uploads/products/images-1769737873700-719390066.jpg',
        '/uploads/products/images-1769737873701-346092140.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['XS', 'S', 'M', 'L'],
      colors: ['Noir', 'Blanc', 'Rose', 'Vert'],
      stock: 100,
      sku: 'CRO-COT-001',
      featured: false,
      bestseller: true,
      isActive: true,
      tags: ['crop top', 'côtelé', 'stretch', 'basique'],
      materials: ['Coton', 'Élasthanne'],
      careInstructions: 'Lavage en machine à 30°C',
      weight: 0.12,
      rating: { average: 4.2, count: 25 },
      views: 350,
      soldCount: 85,
    },
    // Product 22
    {
      name: 'Ensemble Sport Élégant',
      slug: 'ensemble-sport-elegant',
      description: 'Ensemble de sport deux pièces combinant confort et style. Parfait pour le fitness ou un look streetwear décontracté.',
      price: 109.90,
      comparePrice: 149.90,
      images: [
        '/uploads/products/images-1769737881737-537135292.jpg',
        '/uploads/products/images-1769737881737-763825544.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Noir', 'Gris', 'Rose'],
      stock: 55,
      sku: 'ENS-SPO-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['ensemble', 'sport', 'fitness', 'streetwear'],
      materials: ['Polyester', 'Élasthanne'],
      careInstructions: 'Lavage en machine à 30°C',
      weight: 0.5,
      rating: { average: 4.4, count: 13 },
      views: 195,
      soldCount: 31,
    },
    // Product 23
    {
      name: 'Jupe Crayon Fendue',
      slug: 'jupe-crayon-fendue',
      description: 'Jupe crayon avec fente arrière élégante. Coupe ajustée qui sculpte la silhouette avec un tissu stretch confortable.',
      price: 64.90,
      comparePrice: 84.90,
      images: [
        '/uploads/products/images-1769737888613-171545392.jpg',
        '/uploads/products/images-1769737888613-893113098.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Noir', 'Rouge', 'Bleu marine'],
      stock: 45,
      sku: 'JUP-CRA-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['jupe', 'crayon', 'fendue', 'ajustée'],
      materials: ['Polyester', 'Élasthanne'],
      careInstructions: 'Lavage à 30°C',
      weight: 0.25,
      rating: { average: 4.1, count: 10 },
      views: 145,
      soldCount: 22,
    },
    // Product 24
    {
      name: 'Robe Pull Longue',
      slug: 'robe-pull-longue',
      description: 'Robe pull longue et confortable en maille douce. Parfaite pour un look cozy et stylé pendant l\'hiver.',
      price: 109.90,
      comparePrice: 149.90,
      images: [
        '/uploads/products/images-1769737896436-654122997.jpg',
        '/uploads/products/images-1769737896438-886001519.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L'],
      colors: ['Camel', 'Gris', 'Noir'],
      stock: 30,
      sku: 'ROB-PUL-001',
      featured: true,
      bestseller: false,
      isActive: true,
      tags: ['robe', 'pull', 'maille', 'hiver', 'cozy'],
      materials: ['Laine', 'Acrylique'],
      careInstructions: 'Lavage à la main ou programme laine',
      weight: 0.5,
      rating: { average: 4.6, count: 18 },
      views: 260,
      soldCount: 40,
    },
    // Product 25
    {
      name: 'Débardeur Satin Luxe',
      slug: 'debardeur-satin-luxe',
      description: 'Débardeur en satin avec finitions dentelle. Un essentiel féminin et raffiné à porter seul ou sous une veste.',
      price: 44.90,
      comparePrice: 64.90,
      images: [
        '/uploads/products/images-1769737903644-193110810.jpg',
        '/uploads/products/images-1769737903644-194586808.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Noir', 'Champagne', 'Rose poudré'],
      stock: 70,
      sku: 'DEB-SAT-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['débardeur', 'satin', 'dentelle', 'luxe'],
      materials: ['Satin', 'Dentelle'],
      careInstructions: 'Lavage délicat à la main',
      weight: 0.1,
      rating: { average: 4.3, count: 12 },
      views: 160,
      soldCount: 26,
    },
    // Product 26
    {
      name: 'Trench Coat Ceinturé',
      slug: 'trench-coat-ceinture',
      description: 'Trench coat classique avec ceinture à nouer. Une pièce iconique et intemporelle pour mi-saison.',
      price: 169.90,
      comparePrice: 219.90,
      images: [
        '/uploads/products/images-1769737911515-171326181.jpg',
        '/uploads/products/images-1769737911517-451135565.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Beige', 'Noir', 'Kaki'],
      stock: 20,
      sku: 'TRE-COA-001',
      featured: true,
      bestseller: true,
      isActive: true,
      tags: ['trench', 'coat', 'ceinturé', 'mi-saison', 'classique'],
      materials: ['Polyester', 'Coton'],
      careInstructions: 'Nettoyage à sec recommandé',
      weight: 0.8,
      rating: { average: 4.9, count: 22 },
      views: 340,
      soldCount: 52,
    },
    // Product 27
    {
      name: 'Combi-Short Été',
      slug: 'combi-short-ete',
      description: 'Combi-short léger et estival avec motifs tropicaux. Parfait pour les vacances et les journées chaudes.',
      price: 59.90,
      comparePrice: 79.90,
      images: [
        '/uploads/products/images-1769737919724-156324296.jpg',
        '/uploads/products/images-1769737919724-406205684.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L'],
      colors: ['Multicolore', 'Blanc', 'Corail'],
      stock: 50,
      sku: 'COM-SHO-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['combi-short', 'été', 'vacances', 'tropical'],
      materials: ['Viscose', 'Lin'],
      careInstructions: 'Lavage en machine à 30°C',
      weight: 0.2,
      rating: { average: 4.2, count: 9 },
      views: 140,
      soldCount: 18,
    },
    // Product 28
    {
      name: 'Gilet Sans Manches Matelassé',
      slug: 'gilet-sans-manches-matelasse',
      description: 'Gilet matelassé léger et chaud, parfait pour la mi-saison. Se porte sur un pull ou une chemise.',
      price: 79.90,
      comparePrice: 109.90,
      images: [
        '/uploads/products/images-1769737926782-398295780.jpg',
        '/uploads/products/images-1769737926783-452773004.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Noir', 'Beige', 'Vert forêt'],
      stock: 40,
      sku: 'GIL-MAT-001',
      featured: false,
      bestseller: false,
      isActive: true,
      tags: ['gilet', 'matelassé', 'sans manches', 'mi-saison'],
      materials: ['Polyester', 'Duvet synthétique'],
      careInstructions: 'Lavage en machine à 30°C',
      weight: 0.4,
      rating: { average: 4.0, count: 6 },
      views: 100,
      soldCount: 14,
    },
    // Product 29
    {
      name: 'Robe Wrap Portefeuille',
      slug: 'robe-wrap-portefeuille',
      description: 'Robe portefeuille ajustable avec un imprimé floral délicat. Flatteuse pour toutes les morphologies.',
      price: 114.90,
      comparePrice: 154.90,
      images: [
        '/uploads/products/images-1769738487573-240660150.jpg',
        '/uploads/products/images-1769738487574-558594496.jpg',
      ],
      categories: pick(allCatIds, 1),
      productCollection: pick(allColIds, 1)[0],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Floral bleu', 'Floral rose', 'Uni noir'],
      stock: 55,
      sku: 'ROB-WRA-001',
      featured: true,
      bestseller: true,
      isActive: true,
      tags: ['robe', 'portefeuille', 'wrap', 'floral', 'ajustable'],
      materials: ['Jersey', 'Élasthanne'],
      careInstructions: 'Lavage en machine à 30°C',
      weight: 0.3,
      rating: { average: 4.7, count: 26 },
      views: 360,
      soldCount: 63,
    },
  ];
};

const seedProducts = async () => {
  try {
    await connectDB();

    // Fetch existing categories and collections from DB
    const categories = await Category.find({});
    const collections = await Collection.find({});

    if (categories.length === 0) {
      console.log('⚠️  No categories found. Please seed categories first.'.yellow);
      process.exit(1);
    }
    if (collections.length === 0) {
      console.log('⚠️  No collections found. Please seed collections first.'.yellow);
      process.exit(1);
    }

    console.log(`📂 Found ${categories.length} categories and ${collections.length} collections`.cyan);

    // Build ID maps
    const categoryIds = {};
    categories.forEach((cat, i) => {
      categoryIds[cat.slug || cat.name || i] = cat._id;
    });
    const collectionIds = {};
    collections.forEach((col, i) => {
      collectionIds[col.slug || col.name || i] = col._id;
    });

    // Clear existing products
    const deleted = await Product.deleteMany({});
    console.log(`🗑️  Cleared ${deleted.deletedCount} existing products`.yellow);

    // Generate and insert products
    const products = getProducts(categoryIds, collectionIds);
    const created = await Product.insertMany(products);

    console.log(`\n✅ Successfully seeded ${created.length} products!`.green.bold);
    console.log('\n📊 Product Summary:');
    created.forEach((p, i) => {
      console.log(`   ${i + 1}. ${p.name} - ${p.price} DT (${p.images.length} images)`);
    });

    const featuredCount = created.filter(p => p.featured).length;
    const bestsellerCount = created.filter(p => p.bestseller).length;
    console.log(`\n   ⭐ Featured: ${featuredCount}`);
    console.log(`   🏆 Bestsellers: ${bestsellerCount}`);
    console.log(`   📷 Total images: ${created.reduce((sum, p) => sum + p.images.length, 0)}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding products:'.red, error);
    process.exit(1);
  }
};

seedProducts();
