// frontend/src/utils/tunisiaDelegations.js

export const tunisiaDelegations = {
  'Tunis': [
    'Carthage',
    'La Médina',
    'Bab Bhar',
    'Bab Souika',
    'Omrane',
    'Omrane Supérieur',
    'Ettahrir',
    'Cité El Khadra',
    'Bardo',
    'Le Kram',
    'La Goulette',
    'La Marsa',
    'Sidi Bou Saïd',
    'Séjoumi',
    'Ezzouhour',
    'El Hrairia',
    'Sidi Hassine',
    'El Ouardia',
    'El Kabaria',
    'Djebel Jelloud',
    'La Kasba'
  ],
  'Ariana': [
    'Ariana Ville',
    'Soukra',
    'Raoued',
    'Kalâat El Andalous',
    'Sidi Thabet',
    'Ettadhamen',
    'Mnihla'
  ],
  'Ben Arous': [
    'Ben Arous',
    'El Mourouj',
    'Hammam Lif',
    'Hammam Chott',
    'Bou Mhel El Bassatine',
    'Ezzahra',
    'Radès',
    'Mégrine',
    'Mohamedia',
    'Fouchana',
    'Mornag',
    'Nouvelle Médina'
  ],
  'Manouba': [
    'Manouba',
    'Den Den',
    'Douar Hicher',
    'Oued Ellil',
    'Mornaguia',
    'Borj El Amri',
    'El Battan',
    'Tebourba'
  ],
  'Nabeul': [
    'Nabeul',
    'Dar Chaabane El Fehri',
    'Béni Khiar',
    'Korba',
    'Menzel Temime',
    'Mida',
    'Kelibia',
    'Hammam Ghezèze',
    'Haouaria',
    'Takelsa',
    'Soliman',
    'Menzel Bouzelfa',
    'Béni Khalled',
    'Grombalia',
    'Bou Argoub',
    'Hammamet'
  ],
  'Zaghouan': [
    'Zaghouan',
    'Zriba',
    'Bir Mcherga',
    'El Fahs',
    'Nadhour',
    'Saouaf'
  ],
  'Bizerte': [
    'Bizerte Nord',
    'Bizerte Sud',
    'Jarzouna',
    'Mateur',
    'Ghezala',
    'Menzel Bourguiba',
    'Tinja',
    'Ghar El Melh',
    'Menzel Jemil',
    'El Alia',
    'Ras Jebel',
    'Sejenane',
    'Joumine',
    'Utique'
  ],
  'Béja': [
    'Béja Nord',
    'Béja Sud',
    'Amdoun',
    'Nefza',
    'Téboursouk',
    'Tibar',
    'Testour',
    'Goubellat',
    'Mejez El Bab'
  ],
  'Jendouba': [
    'Jendouba',
    'Jendouba Nord',
    'Bou Salem',
    'Tabarka',
    'Aïn Draham',
    'Fernana',
    'Balta Bou Aouen',
    'Ghardimaou',
    'Oued Meliz'
  ],
  'Kef': [
    'El Kef Est',
    'El Kef Ouest',
    'Nebeur',
    'Sakiet Sidi Youssef',
    'Tajerouine',
    'Kalaat Senan',
    'Kalâat Khasba',
    'Jérissa',
    'El Ksour',
    'Dahmani',
    'Sers'
  ],
  'Siliana': [
    'Siliana Nord',
    'Siliana Sud',
    'Bouarada',
    'Gaâfour',
    'El Krib',
    'Bou Rouis',
    'Bargou',
    'El Aroussa',
    'Kesra',
    'Rouhia',
    'Makthar'
  ],
  'Kairouan': [
    'Kairouan Nord',
    'Kairouan Sud',
    'Chebika',
    'Sbikha',
    'Oueslatia',
    'Haffouz',
    'El Alâa',
    'Hajeb El Ayoun',
    'Nasrallah',
    'Cherarda',
    'Bouhajla'
  ],
  'Kasserine': [
    'Kasserine Nord',
    'Kasserine Sud',
    'Ezzouhour',
    'Hassi El Frid',
    'Sbeitla',
    'Sbiba',
    'Djedeliane',
    'El Ayoun',
    'Thala',
    'Hidra',
    'Foussana',
    'Fériana',
    'Majel Bel Abbès'
  ],
  'Sidi Bouzid': [
    'Sidi Bouzid Ouest',
    'Sidi Bouzid Est',
    'Cebbala Ouled Asker',
    'Bir El Hafey',
    'Sidi Ali Ben Aoun',
    'Menzel Bouzaiane',
    'Meknassy',
    'Souk Jedid',
    'Mezzouna',
    'Regueb',
    'Ouled Haffouz',
    'Jilma'
  ],
  'Sousse': [
    'Sousse Ville',
    'Sousse Riadh',
    'Sousse Jawhara',
    'Sousse Sidi Abdelhamid',
    'Hammam Sousse',
    'Akouda',
    'Kalâa Kebira',
    'Sidi Bou Ali',
    'Hergla',
    'Enfida',
    'Bouficha',
    'Kondar',
    'Sidi El Heni',
    'M\'saken',
    'Kalâa Seghira',
    'Zaouiet Sousse'
  ],
  'Monastir': [
    'Monastir',
    'Ouerdanine',
    'Sahline',
    'Zéramdine',
    'Béni Hassen',
    'Jammel',
    'Téboulba',
    'Ksar Hellal',
    'Ksibet El Médiouni',
    'Sayada-Lamta-Bou Hajar',
    'Moknine',
    'Bekalta',
    'Bembla'
  ],
  'Mahdia': [
    'Mahdia',
    'Bou Merdes',
    'Ouled Chamekh',
    'Chorbane',
    'Hebira',
    'Essouassi',
    'El Djem',
    'Kerker',
    'Chebba',
    'Melloulèche',
    'Sidi Alouane',
    'Ksour Essef'
  ],
  'Sfax': [
    'Sfax Ville',
    'Sfax Ouest',
    'Sakiet Ezzit',
    'Sakiet Eddaïer',
    'Sfax Sud',
    'Thyna',
    'Agareb',
    'Jebiniana',
    'El Amra',
    'El Hencha',
    'Menzel Chaker',
    'Ghraïba',
    'Bir Ali Ben Khélifa',
    'Skhira',
    'Mahares',
    'Kerkennah'
  ],
  'Gafsa': [
    'Gafsa Nord',
    'Gafsa Sud',
    'Sidi Aïch',
    'El Ksar',
    'Moularès',
    'Redeyef',
    'Métlaoui',
    'Mdhila',
    'El Guettar',
    'Belkhir',
    'Sned'
  ],
  'Tozeur': [
    'Tozeur',
    'Degache',
    'Tameghza',
    'Nefta',
    'Hazoua'
  ],
  'Kebili': [
    'Kebili Sud',
    'Kebili Nord',
    'Souk Lahad',
    'Douz Nord',
    'Douz Sud',
    'El Faouar',
    'Jemna'
  ],
  'Gabès': [
    'Gabès Ville',
    'Gabès Ouest',
    'Gabès Sud',
    'Ghannouch',
    'El Métouia',
    'Menzel El Habib',
    'Nouvelle Matmata',
    'Matmata',
    'Mareth',
    'El Hamma'
  ],
  'Medenine': [
    'Medenine Nord',
    'Medenine Sud',
    'Beni Khedache',
    'Ben Gardane',
    'Zarzis',
    'Houmt Souk',
    'Midoun',
    'Ajim',
    'Sidi Makhlouf'
  ],
  'Tataouine': [
    'Tataouine Nord',
    'Tataouine Sud',
    'Ghomrassen',
    'Dhehiba',
    'Remada',
    'Bir Lahmar',
    'Smâr'
  ]
};

// Get delegations for a specific governorate
export const getDelegationsByGovernorate = (governorate) => {
  return tunisiaDelegations[governorate] || [];
};

// Get all delegations as a flat array
export const getAllDelegations = () => {
  return Object.values(tunisiaDelegations).flat().sort();
};
